import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import  {Providers} from "./providers";
import { queryClient } from '@/lib/queryClient';

const inter = Inter({ subsets: ['latin'], variable: '--font-inter' });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`${inter.variable} `}>
      <body className="antialiased bg-[#121212] text-white">
        <Providers>{children}</Providers>
      </body>
    </html>
  );
}
