import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import AppHeader from "@/components/common/app-header";
import Footer from "@/components/common/app-footer";
import { fetchCourses } from "@/queries/courses";
import { fetchCategories } from "@/queries/categories";
import { CourseCardProps } from "@/types/skills";
import { CategoryFolder } from "@/types/skills";

const inter = Inter({ subsets: ["latin"], variable: "--font-inter" });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  let courses: string[] = [];
  let categories: string[] = [];
  let error: string | null = null;

  try {
    const fetchedCourses = await fetchCourses();
    courses = fetchedCourses.map((course: CourseCardProps) => course.title);
    const fetchedCategories = await fetchCategories();
    categories = fetchedCategories.map((category: CategoryFolder) => category.name);
  } catch (err) {
    error = "Failed to load data";
  }

  return (
    <html lang="en" className={`${inter.variable}`}>
      <body>
        <AppHeader courses={courses} categories={categories} error={error} />
        {children}
        <Footer courses={courses} categories={categories} error={error} />
      </body>
    </html>
  );
}
