import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import AppHeader from "@/components/common/app-header";
import Footer from "@/components/common/app-footer";
import { fetchCourses } from "@/queries/courses";
import { fetchCategories } from "@/queries/categories";
import { CourseCardProps } from "@/types/skills";
import { CategoryFolder } from "@/types/skills";

const inter = Inter({ subsets: ["latin"], variable: "--font-inter" });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  let courses: string[] = [];
  let categories: string[] = [];
  let error: string | null = null;

  // Mock universities data - you can replace this with actual data fetching
  const universities = [
    'Cairo University', 'Ain Shams University', 'Alexandria University', 'Mansoura University',
    'Zagazig University', 'Tanta University', 'Helwan University', 'Benha University',
    'Assiut University', 'Suez Canal University', 'Minia University', 'South Valley University'
  ];

    const fetchedCourses = await fetchCourses();
    courses = fetchedCourses.map((course: CourseCardProps) => course.title);
    const fetchedCategories = await fetchCategories();
    categories = fetchedCategories.map((category: CategoryFolder) => category.name);
  

  return (
    <html lang="en" className={`${inter.variable}`}>
      <body>
        <AppHeader courses={courses} categories={categories} universities={universities} error={error} />
        {children}
        <Footer courses={courses} categories={categories} error={error} />
      </body>
    </html>
  );
}
